version: "3.9"

services:
  ethereum_node:
    image: ghcr.io/foundry-rs/foundry:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - 8545:8545
      - 8546:8545
    entrypoint:
      - anvil
      - --host
      - "0.0.0.0"
    depends_on:
      mysql:
        condition: service_healthy

  ipfs:
    image: ipfs/kubo:latest
    restart: always
    ports:
      - '4001:4001'
      - '4001:4001/udp'
      - '8080:8080'
      - '5001:5001'

  mysql:
    image: mysql:5.6
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'burnfeed'
      MYSQL_USER: 'burnfeed'
      MYSQL_PASSWORD: 'burnfeed'
      MYSQL_ROOT_PASSWORD: 'burnfeed'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
