name: "CI"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.0
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m

  integration_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      INDEXER_DIR: indexer
      PROTOCOL_DIR: protocol

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          repository: AlZaeemOdion/burnfeed-indexer
          path: ${{ env.INDEXER_DIR }}

      - uses: actions/checkout@v3
        with:
          repository: AlZaeemOdion/burnfeedprotocol
          path: ${{ env.PROTOCOL_DIR }}
          ref: main-1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true
          cache-dependency-path: ${{ env.INDEXER_DIR }}/go.sum

      - name: Install protocol dependencies
        working-directory: ${{ env.PROTOCOL_DIR }}
        run: git config --global user.name "Odion" && git config --global user.email "AlZaeemOdion@proton.me" && forge install OpenZeppelin/openzeppelin-contracts

      - name: Build
        working-directory: ${{ env.INDEXER_DIR }}
        run: make build

      - name: Test
        working-directory: ${{ env.INDEXER_DIR }}
        run: |
          IPFS_ENDPOINT=https://ipfs.infura.io:5001 IPFS_API_KEY=${{secrets.IPFS_API_KEY}} IPFS_API_SECRET=${{secrets.IPFS_API_SECRET}} BURN_FEED_DIR=${GITHUB_WORKSPACE}/${PROTOCOL_DIR} make test
